SDK-1767: Allow retrieval of frame for an id document page
getyoti/yoti-java-sdk pull request #222
Opened 2020-10-05 16:46 UTC by MrBurtyyy

2020-10-05 17:02 UTC, davidgrayston approved these changes

2020-10-05 17:03 UTC, echarrod approved these changes

2020-10-05 17:44 UTC, davidgrayston requested changes
We also need to update the demo to display the frames

2020-10-06 17:24 UTC, davidgrayston approved these changes
@MrBurtyyy I've copied the HTML from other SDK demos in 42de1a6 for multiple pages with frames

2020-10-07 07:33 UTC, echarrod approved these changes

2020-10-07 09:38 UTC, merged