Release 3.0.0
getyoti/yoti-java-sdk pull request #262
Opened 2021-01-18 17:48 UTC by MrBurtyyy

## Changes

### Use of `ServiceLocator`

- The use of the `ServiceLocator` class has been dropped in order to simplify the development process of the SDK.
- The `yoti-sdk-api` and `yoti-sdk-impl` modules have been merged, with the `yoti-sdk-impl` module then being removed.

### Builders

All builders have now been in-lined into their respective classes, and the use of factories has been dropped (they are no longer neccessary due to the removal of the use of `ServiceLocator`).  Example below:

```java
YotiClient client = YotiClientBuilder.newInstance().build() // OLD

YotiClient client = YotiClient.builder().build() // NEW
```

2021-01-29 16:00 UTC, echarrod requested changes
We need to update the versions from `3.0.0-SNAPSHOT` to `3.0.0` don't we?

2021-01-29 16:00 UTC, echarrod commented on README.md
> +    <version>3.0.0-SNAPSHOT</version>
```suggestion
    <version>3.0.0</version>
```

2021-01-29 16:00 UTC, echarrod commented on README.md
> +`compile group: 'com.yoti', name: 'yoti-sdk-api', version: '3.0.0-SNAPSHOT'`
```suggestion
`compile group: 'com.yoti', name: 'yoti-sdk-api', version: '3.0.0'`
```

2021-01-29 16:07 UTC, MrBurtyyy commented
> We need to update the versions from `3.0.0-SNAPSHOT` to `3.0.0` don't we?

These will be done just before release.  The reason we don't do it straight away is so QA can easily run the demo projects without having to manually change the versions back to `-SNAPSHOT` versions

2021-02-02 11:07 UTC, echarrod commented on yoti-sdk-api/src/main/java/com/yoti/api/client/docs/DocScanClient.java
> +        // FIXME: Should this really be a static property?????
```suggestion
```

2021-03-01 11:17 UTC, bucky-boy approved these changes
looks good to me.

2021-03-01 11:23 UTC, jlmartyres approved these changes

2021-03-01 11:39 UTC, echarrod approved these changes
:rocket:

2021-03-01 15:15 UTC, merged