SDK-2115: Support CIFAS Identity check result
getyoti/yoti-java-sdk pull request #320
Opened 2022-04-25 15:02 UTC by irotech

2022-04-25 17:21 UTC, MrBurtyyy requested changes
This check cannot be requested like traditional checks, so we can remove any bits to do with requesting the check

2022-04-25 17:21 UTC, MrBurtyyy commented on yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/create/check/RequestedThirdPartyIdentityFraudOneCheck.java
> +public class RequestedThirdPartyIdentityFraudOneCheck extends RequestedCheck<RequestedThirdPartyIdentityFraudOneConfig> {
`THIRD_PARTY_IDENTITY_FRAUD_1` checks cannot be requested like regular checks (they are part of the Identity Profile flow).  This isn't needed :)

2022-04-26 11:50 UTC, BenSmithYoti requested changes
Comment on now (I believe) unused file. 
Other than that LGTM. Thanks Vince.

2022-04-26 11:50 UTC, BenSmithYoti commented on yoti-sdk-api/src/test/java/com/yoti/api/client/docs/session/create/check/CheckType.java
> +public enum CheckType {
Think this is unused now that the extra test file ..api/client/docs/session/create/check/RequestedThirdPartyIdentityFraudOneCheckTest.java has been removed with second commit

2022-04-26 12:01 UTC, BenSmithYoti commented
Oh, just noticed (waiting to see what @echarrod says for dotnet side) but we have this HTML template file for the IDV demo app https://github.com/getyoti/yoti-dotnet-sdk/blob/master/src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml which I feel might need an update to include this new type of check. If we do want that I believe that there is an equivalent (index.html maybe?) in the java repo. @echarrod any input on this would be great please, then I can finish my PR. Thanks

2022-04-26 12:02 UTC, BenSmithYoti commented
@MrBurtyyy do you know about this perhaps? Is this demo UI wanting to be updated in this iteration? https://github.com/getyoti/yoti-java-sdk/pull/320#issuecomment-1109708226

2022-04-26 12:17 UTC, echarrod commented
> Oh, just noticed (waiting to see what @echarrod says for dotnet side) but we have this HTML template file for the IDV demo app https://github.com/getyoti/yoti-dotnet-sdk/blob/master/src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml which I feel might need an update to include this new type of check. If we do want that I believe that there is an equivalent (index.html maybe?) in the java repo. @echarrod any input on this would be great please, then I can finish my PR. Thanks

Yep we'll need that so Darren to verify that this new check comes through in the response correctly :+1:

2022-04-26 14:49 UTC, BenSmithYoti approved these changes
LGTM

2022-04-26 14:56 UTC, closed without merging